<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="USPHXAWNC0038Y6" name="edu.apollogrp.tests.UCPSmokeTests.UCPSmokeTests_CallType" tests="2" failures="0" timestamp="21 Feb 2017 17:55:54 GMT" time="1156.708" errors="1">
  <testcase name="qualficationTransfer" time="171.429" classname="edu.apollogrp.tests.UCPSmokeTests.UCPSmokeTests_CallType"/>
  <testcase name="erInboundCall" time="985.279" classname="edu.apollogrp.tests.UCPSmokeTests.UCPSmokeTests_CallType">
    <error type="java.lang.AssertionError" message="exception in checkContactTab">
      <![CDATA[java.lang.AssertionError: exception in checkContactTab
	at org.testng.Assert.fail(Assert.java:94)
	at com.apollo.agentscripting.er_inboundcall.ERInbound_CallType.checkContactTab(ERInbound_CallType.java:219)
	at com.apollo.agentscripting.er_inboundcall.ERInbound_CallType.clickCaseInfo(ERInbound_CallType.java:195)
	at com.apollo.agentscripting.er_inboundcall.ERInbound_CallType.getCall(ERInbound_CallType.java:165)
	at com.apollo.agentscripting.er_inboundcall.ERInbound_CallType.getAgentReady(ERInbound_CallType.java:149)
	at com.apollo.agentscripting.er_inboundcall.ERInbound_CallType.clickSubmit(ERInbound_CallType.java:113)
	at com.apollo.agentscripting.er_inboundcall.ERInbound_CallType.clickPassword(ERInbound_CallType.java:94)
	at com.apollo.agentscripting.er_inboundcall.ERInbound_CallType.clickUserName(ERInbound_CallType.java:72)
	at com.apollo.agentscripting.er_inboundcall.ERInbound_CallType.setUp(ERInbound_CallType.java:49)
	at edu.apollogrp.tests.UCPSmokeTests.UCPSmokeTests_CallType.erInboundCall(UCPSmokeTests_CallType.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- erInboundCall -->
</testsuite> <!-- edu.apollogrp.tests.UCPSmokeTests.UCPSmokeTests_CallType -->
