<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="USPHXAWNC0038Y6" name="final" tests="7" failures="1" timestamp="28 Dec 2016 23:05:44 GMT" time="5.834" errors="0">
  <testcase name="runSelenium" time="0.009" classname="com.mkyong.testng.examples.group.TestSelenium"/>
  <testcase name="runSelenium1" time="0.004" classname="com.mkyong.testng.examples.group.TestSelenium"/>
  <testcase name="runSelenium" time="0.004" classname="com.mkyong.testng.examples.group.TestGroup"/>
  <testcase name="runSelenium1" time="0.004" classname="com.mkyong.testng.examples.group.TestGroup">
    <failure type="java.lang.AssertionError" message="expected [6] but found [7]">
      <![CDATA[java.lang.AssertionError: expected [6] but found [7]
	at com.mkyong.testng.examples.group.TestGroup.runSelenium1(TestGroup.java:36)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- runSelenium1 -->
  <testcase name="testConnectMsSQL" time="0.005" classname="com.mkyong.testng.examples.group.TestGroup"/>
  <testcase name="testConnectOracle" time="0.003" classname="com.mkyong.testng.examples.group.TestGroup"/>
  <testcase name="runFinal" time="0.0" classname="com.mkyong.testng.examples.group.TestGroup">
    <skipped/>
  </testcase> <!-- runFinal -->
</testsuite> <!-- final -->
